### ISSUE TITLE
Some passwords not working after db migration

### ISSUE THREAD

**Issue by grandeljay** [openwall/phpass#1]
Hello,

I am using some [very old school software](https://www.modified-shop.org/) which relies on phpass to generate and validate user passwords.

After migrating the database, some, but not all users are not able to log in anymore and have to reset their password. Since the hashes are the same I am totally confused why.

Do you have any idea where or how I can debug this?

Thanks.

**Comment by solardiz** [comment]
Hi @grandeljay. If you post first 4 chars of a hash that continued working and 4 chars of a hash that stopped working, maybe I'd have an idea. Even if they are the same.

**Comment by grandeljay** [comment]
Hey, thanks for responding!

Admittedly, it turned out that said users were using the wrong password.

Sorry about that.
